name: ESLint
on:
  workflow_call:
    inputs:
        extensionName:
          description: 'Extension name'
          required: true
          type: string
        allincartVersion:
          required: false
          type: string
          default: '.auto'
        allincartVersionFallback:
          required: false
          type: string
          default: trunk
        allincart-repository:
          description: The allincart repository to checkout
          type: string
          default: allincart-org/allincart

jobs:
  run:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: allincart-org/github-actions/allincart-version@main
        with:
          fallback: ${{ inputs.allincartVersionFallback }}
          repo: ${{ inputs.allincart-repository }}
        id: version
        if: ${{ inputs.allincartVersion == '.auto' || inputs.allincartVersion == '' }}
      - name: Clone Shopware
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.allincart-repository || 'allincart-org/allincart' }}
          ref: ${{ steps.version.outputs.allincart-version || inputs.allincartVersion }}
      - name: Clone Extension
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ inputs.extensionName }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install admin deps
        shell: bash
        working-directory: src/Administration/Resources/app/administration
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Install Plugin Dependencies
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm install --no-audit --no-fund --prefer-offline

      - name: Run ESLint
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm run lint
