name: Test actions
on:
  pull_request:

jobs:
    allincart-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - id: version
              uses: ./allincart-version
              with:
                fallback: ""
            - name: Check allincart-version is never empty 
              run: |
                SHOPWARE_VERSION="${{ steps.version.outputs.allincart-version }}"
                echo "allincart-version: '${SHOPWARE_VERSION}'"
                if [[ -z "${SHOPWARE_VERSION}" ]]; then
                    echo 'allincart-version should not be empty'
                    exit 1
                fi

                


